### ISSUE TITLE
Python 3.8 release

### ISSUE THREAD

**Issue by lordmauve** [skogler/mapbox_earcut_python#2]
Hi, thanks for this. I have just switched over from a pure Python implementation to this, and it works great. Here's an image for your showcase, made with [wasabi2d](/lordmauve/wasabi2d):

![image](https://user-images.githubusercontent.com/617224/68162706-8d06a400-ff50-11e9-9a08-9ffcf245e56c.png)

Just wondering if you are interested to release wheels for Python 3.8?

**Comment by hetsch** [comment]
Hi,
yes, Python 3.8 would be awesome! 
Also, have you seen that mapbox/earcut released a new version 2.2.2? 
Thank you for this very handy wrapper!

**Comment by einarf** [comment]
I think most people have moved to 3.8 by now. It would be great to have 3.8 wheels to keep this package relevant. It's an awesome project.

**Comment by skogler** [comment]
Hi, sorry for the absence, did not check the notifications in a long time here and I am still stuck on an older Python version at work  ;-)

I did update the Azure pipelines now to build a 3.8 wheel as well, build is currently running.

There is also one more fix from revision 5d554768316a7931bcc999dc8d7675d58be1ac45 of the `mapbox/earcut.hpp` project included in the new release. 

The version of this package refers to the latest release version of that project, which is quite a bit older, since they did not make any releases since. but not sure what their *newest* git version would be.  I am currently bumping up the minor version since PYPI does not let me add a patch version...

Maybe I should just use my own versions instead since the current versioning does not really match up with the reference due to the patches etc.

**Comment by lordmauve** [comment]
Cool, thanks!
